#ifndef __GLV_FLEX_PANEL_H
#define __GLV_FLEX_PANEL_H


#include <glv/stack_panel.h>

#define VM_FLEX_PANEL_SET_VERTICAL VM_STACK_PANEL_SET_VERTICAL
#define VM_FLEX_PANEL_SET_HORISONTAL VM_STACK_PANEL_SET_HORISONTAL

#define VM_FLEX_PANEL_SET_JUSTIFY_START VM_USER_FIRST + 20
#define VM_FLEX_PANEL_SET_JUSTIFY_CENTER VM_USER_FIRST + 21
#define VM_FLEX_PANEL_SET_JUSTIFY_SPACE_BETWEEN VM_USER_FIRST + 22
#define VM_FLEX_PANEL_SET_JUSTIFY_SPACE_AROUND VM_USER_FIRST + 23
#define VM_FLEX_PANEL_SET_JUSTIFY_SPACE_EVENLY VM_USER_FIRST + 24

#define VM_FLEX_PANEL_SET_JUSTIFY_STRATCH_PAD VM_USER_FIRST + 25
#define VM_FLEX_PANEL_SET_JUSTIFY_STRATCH_MIN_MAX VM_USER_FIRST + 26
#define VM_FLEX_PANEL_SET_JUSTIFY_NO_STRATCH VM_USER_FIRST + 27

#define VM_FLEX_PANEL_SET_ALIGN_CENTER VM_USER_FIRST + 28
#define VM_FLEX_PANEL_SET_ALIGN_LEFT VM_USER_FIRST + 29
#define VM_FLEX_PANEL_SET_ALIGN_RIGHT VM_USER_FIRST + 30

#define VM_FLEX_PANEL_SET_ALIGN_STRATCH VM_USER_FIRST + 31
#define VM_FLEX_PANEL_SET_ALIGN_STRATCH_MIN_MAX VM_USER_FIRST + 33
#define VM_FLEX_PANEL_SET_ALIGN_STRATCH_PAD_AROUND VM_USER_FIRST + 34
#define VM_FLEX_PANEL_SET_ALIGN_STRATCH_PAD_LEFT VM_USER_FIRST + 35
#define VM_FLEX_PANEL_SET_ALIGN_STRATCH_PAD_RIGHT VM_USER_FIRST + 36

extern ViewProc glv_flex_panel_proc;

#endif //__GLV_FLEX_PANEL_H
