#ifndef GLV_PRIVATE_H
#define GLV_PRIVATE_H


#define log_printf __glv_private_log_printf
#define should_redraw __glv_private_should_redraw
#define default_on_sdl_event __glv_private_default_on_sdl_event

#define init_draw_texture_ifninit __glv_private_init_draw_texture_ifninit
#define free_draw_texture __glv_private_free_draw_texture

#define draw_texture_vert __glv_private_draw_texture_vert
#define draw_texture_frag __glv_private_draw_texture_frag

#define draw_glyph_vert __glv_private_glyph_vert
#define draw_glyph_frag __glv_private_glyph_frag

#endif //GLV_PRIVATE_H
