#ifndef GLV_PRIVATE_H
#define GLV_PRIVATE_H


#define log_printf __glv_private_log_printf
#define should_redraw __glv_private_should_redraw
#define default_on_sdl_event __glv_private_default_on_sdl_event

#define init_draw_texture __glv_private_init_draw_texture
#define free_draw_texture __glv_private_free_draw_texture

#define init_draw_circle __glv_private_init_draw_circle_program
#define free_draw_circle __glv_private_free_draw_circle_program

#define init_draw_triangle __glv_private_init_draw_triangle_program
#define free_draw_triangle __glv_private_free_draw_triangle_program


#define draw_texture_vert __glv_private_draw_texture_vert
#define draw_texture_frag __glv_private_draw_texture_frag

#define draw_glyph_vert __glv_private_glyph_vert
#define draw_glyph_frag __glv_private_glyph_frag

#define draw_circle_vert __glv_private_circle_vert
#define draw_circle_frag __glv_private_circle_frag

#define draw_triangle_vert __glv_private_triangle_vert
#define draw_triangle_frag __glv_private_triangle_frag



#endif //GLV_PRIVATE_H
